### PR TITLE
Grunt config

### PR DESCRIPTION
**Pull request by ryenbeatty**
- add production task
- minify js in production (except '_' prefix)

### CODE REVIEW

**Comment by tommaitland** [comment]
Merged in with 5727619fa2c22801587a4c77a88f60cdad322646

**Comment by ryenjbeatty** [comment]
Nice!

**Comment by moist-hat** [comment]
Beauty!

**Comment by tommaitland** [comment]
Reopened, it looks like the changes stopped browser sync working, and I've been noticing some issues with the watch task. Lets retest, get browser sync working then merge again. In the meantime I've reverted the commits on master.

**Pull request closed without merging**
